// <auto-generated />
using ETicaret.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ETicaret.Migrations
{
    [DbContext(typeof(ETicaretContext))]
    [Migration("20210320091808_Yapilandir")]
    partial class Yapilandir
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ETicaret.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Adi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("ETicaret.Models.KategoriUrun", b =>
                {
                    b.Property<int>("UrunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UrunId", "KategoriId");

                    b.HasIndex("KategoriId");

                    b.ToTable("KategorilerVeUrunler");
                });

            modelBuilder.Entity("ETicaret.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("isAdmin")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ETicaret.Models.Resim", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dosyaAdi")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("UrunuId");

                    b.ToTable("Resimler");
                });

            modelBuilder.Entity("ETicaret.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("ETicaret.Models.KategoriUrun", b =>
                {
                    b.HasOne("ETicaret.Models.Kategori", "Kategori")
                        .WithMany("KategoriUrunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ETicaret.Models.Urun", "Urun")
                        .WithMany("KategoriUrunler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("ETicaret.Models.Resim", b =>
                {
                    b.HasOne("ETicaret.Models.Urun", "Urunu")
                        .WithMany("Resimler")
                        .HasForeignKey("UrunuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urunu");
                });

            modelBuilder.Entity("ETicaret.Models.Kategori", b =>
                {
                    b.Navigation("KategoriUrunler");
                });

            modelBuilder.Entity("ETicaret.Models.Urun", b =>
                {
                    b.Navigation("KategoriUrunler");

                    b.Navigation("Resimler");
                });
#pragma warning restore 612, 618
        }
    }
}
